### PR TITLE
Shell.nix created

### PR DESCRIPTION
**Pull request by ZwerdDPU**
## Issue

This change includes support for nix-based environments in the project via a nix shell file.

There is not currently an issue for this item.

I am not sure if the submodules are updated correctly.
Thanks!

## Checklist

All of these should be ticked off before you submit the PR.

- [X] I ran `just verify` locally and it succeeded.
- [x] Issue was given <span style="color: #FF4400">go ahead</span> and is linked above **OR** I have included justification for a minor change.
- [X] Unit tests for my changes are not included because no functionality was changed.

### CODE REVIEW

**Comment by V0ldek** [comment]
Is there a way to automatically verify that the `nix` shell is valid?

Ideally I'd like a CI action that automatically checks that we can build the project by just using that nix file and running a build command.

**Comment by V0ldek** [comment]
Seems you've edited the benchmarks here as well, but the benchmark edit is not published anywhere. You need to either separate this nix file from the benchmark change, or first create a PR for the the benchmark change in the benchmark repo and then this will be mergeable.

**Comment by ZwerdDPU** [comment]
Nix should now build itself with the nix-shell workflow now.  Not super performant (3-4 minute runtime :sweat_smile:), but I'm sure there's some sort of cache which can be examined in the near future.

The submodules should also be fixed at this point.

**Comment by V0ldek** [comment]
Can we get Nix to also install `cargo-hack`? It's needed to run full tests. Technically the `justfile` installs it first, but if we're going for Nix we can go all the way, right?

Other than LGTM. Other pipelines take 5-7 minutes even with caching to run tests, and this one can run in parallel, so there's no timing issue.

**Comment by ZwerdDPU** [comment]
> Can we get Nix to also install `cargo-hack`? It's needed to run full tests. Technically the `justfile` installs it first, but if we're going for Nix we can go all the way, right?

Yep.  I've added `cargo-hack` to the nix-shell and just is seeing the package as already installed.

**Review by V0ldek — APPROVED** [review]

**Pull request merged**
